name: Deployment
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t srinathr2001/next-js-app
    - run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_NAME}} --password-stdin
    - run: docker push srinathr2001/next-js-app:latest


     